FROM openjdk:17

WORKDIR /app

COPY . .

# Baixa o JUnit 4
RUN curl -L -o junit-4.13.2.jar https://search.maven.org/remotecontent?filepath=junit/junit/4.13.2/junit-4.13.2.jar && \
    curl -L -o hamcrest-core-1.3.jar https://search.maven.org/remotecontent?filepath=org/hamcrest/hamcrest-core/1.3/hamcrest-core-1.3.jar

RUN javac -cp .:junit-4.13.2.jar Conversor.java ConversorTest.java

CMD ["java", "-cp", ".:junit-4.13.2.jar:hamcrest-core-1.3.jar", "org.junit.runner.JUnitCore", "ConversorTest"]
