# Usa imagem oficial do Java
FROM openjdk:17

# Define o diretório de trabalho dentro do container
WORKDIR /app

# Copia os arquivos do projeto para dentro do container
COPY . .

# Compila os arquivos .java
RUN javac Conversor.java